// import {
//   bike2,
//   bike2f1,
//   bike2f2,
//   bike2f3,
//   bike3,
//   bike3f1,
//   bike3f2,
//   bike3f3,
//   bike4,
//   bike4f1,
//   bike4f2,
//   bike4f3,
//   bike5,
//   bike5f1,
//   bike5f2,
//   bike5f3,
//   bike6,
//   bike6f1,
//   bike6f2,
//   bike6f3,
//   bike7,
//   bike7f1,
//   bike7f2,
//   bike7f3,
//   bike8,
//   bike8f1,
//   bike8f2,
//   bike8f3,
//   bike9,
//   bike9f1,
//   bike9f2,
//   bike9f3,
//   bike10,
//   bike10f1,
//   bike10f2,
//   bike10f3,
//   bike11,
//   bike11f1,
//   bike11f2,
//   bike11f3,
//   bike12,
//   bike12f1,
//   bike12f2,
//   bike12f3,
// } from "./bikesImages";
// import axios from "axios";

// export const bikes = axios
//   .get("http://localhost:8000/bikes?limit=3&page=1")
//   .then((res) => {
//     return res.data;
//   })
//   .catch((err) => {
//     console.log(err);
//   });

// [
//   {
//     src: "http://localhost:8000/api/bikes/bikesImages/bike1/bike1.jpg",
//     alt: "bike1",
//     id: 1,
//     category: "Cube",
//     bikeName: "Cube Reaction Hybrid Pro",
//     price: 2700.0,
//     srcArray: [
//       {
//         id: 1,
//         src: "http://localhost:8000/api/bikes/bikesImages/bike1/bike11.jpg",
//       },
//       {
//         id: 2,
//         src: "http://localhost:8000/api/bikes/bikesImages/bikeLogo/logoebike.png",
//       },
//       {
//         id: 3,
//         src: "http://localhost:8000/api/bikes/bikesImages/bikeLogo/logoebike.png",
//       },
//       {
//         id: 4,
//         src: "http://localhost:8000/api/bikes/bikesImages/bikeLogo/logoebike.png",
//       },
//     ],
//   },

//   {
//     src: bike2,
//     alt: "bike2",
//     id: 2,
//     category: "Vitus",
//     bikeName: "Vitus E-substance Carbon",
//     price: 4300.0,
//     srcArray: [
//       { id: 1, src: bike2 },
//       { id: 2, src: bike2f1 },
//       { id: 3, src: bike2f2 },
//       { id: 4, src: bike2f3 },
//     ],
//   },
//   {
//     src: bike3,
//     alt: "bike3",
//     id: 3,
//     category: "Cube",
//     bikeName: "Cube Ella Ride Hybrid",
//     price: 3700.0,
//     srcArray: [
//       { id: 1, src: bike3 },
//       { id: 2, src: bike3f1 },
//       { id: 3, src: bike3f2 },
//       { id: 4, src: bike3f3 },
//     ],
//   },
//   {
//     src: bike4,
//     alt: "bike4",
//     id: 4,
//     category: "Cube",
//     bikeName: "Cube Reaction Hybrid SLT",
//     price: 5000.0,
//     srcArray: [
//       { id: 1, src: bike4 },
//       { id: 2, src: bike4f1 },
//       { id: 3, src: bike4f2 },
//       { id: 4, src: bike4f3 },
//     ],
//   },
//   {
//     src: bike5,
//     alt: "bike5",
//     id: 5,
//     category: "Orbea",
//     bikeName: "Orbea Vibe H10",
//     price: 5250.0,
//     srcArray: [
//       { id: 1, src: bike5 },
//       { id: 2, src: bike5f1 },
//       { id: 3, src: bike5f2 },
//       { id: 4, src: bike5f3 },
//     ],
//   },
//   {
//     src: bike6,
//     alt: "bike6",
//     id: 6,
//     category: "Orbea",
//     bikeName: "Orbea Vibe H10 EQ,",
//     price: 4100.0,
//     srcArray: [
//       { id: 1, src: bike6 },
//       { id: 2, src: bike6f1 },
//       { id: 3, src: bike6f2 },
//       { id: 4, src: bike6f3 },
//     ],
//   },
//   {
//     src: bike7,
//     alt: "bike7",
//     id: 7,
//     category: "Cube",
//     bikeName: "Cube Acid Hybrid Rookie",
//     price: 3500.0,
//     srcArray: [
//       { id: 1, src: bike7 },
//       { id: 2, src: bike7f1 },
//       { id: 3, src: bike7f2 },
//       { id: 4, src: bike7f3 },
//     ],
//   },
//   {
//     src: bike8,
//     alt: "bike8",
//     id: 8,
//     category: "Orbea",
//     bikeName: "Orbea Vibe Mid H30",
//     price: 3800.0,
//     srcArray: [
//       { id: 1, src: bike8 },
//       { id: 2, src: bike8f1 },
//       { id: 3, src: bike8f2 },
//       { id: 4, src: bike8f3 },
//     ],
//   },
//   {
//     src: bike9,
//     alt: "bike9",
//     id: 9,
//     category: "Orbea",
//     bikeName: "Orbea Keram 10",
//     price: 3950.0,
//     srcArray: [
//       { id: 1, src: bike9 },
//       { id: 2, src: bike9f1 },
//       { id: 3, src: bike9f2 },
//       { id: 4, src: bike9f3 },
//     ],
//   },
//   {
//     src: bike10,
//     alt: "bike10",
//     id: 10,
//     category: "Cube",
//     bikeName: "Cube Supreme Hybrid ONE",
//     price: 3600.0,
//     srcArray: [
//       { id: 1, src: bike10 },
//       { id: 2, src: bike10f1 },
//       { id: 3, src: bike10f2 },
//       { id: 4, src: bike10f3 },
//     ],
//   },
//   {
//     src: bike11,
//     alt: "bike11",
//     id: 11,
//     category: "Cube",
//     bikeName: "Cube Nuride Hybrid EXC",
//     price: 4500.0,
//     srcArray: [
//       { id: 1, src: bike11 },
//       { id: 2, src: bike11f1 },
//       { id: 3, src: bike11f2 },
//       { id: 4, src: bike11f3 },
//     ],
//   },
//   {
//     src: bike12,
//     alt: "bike12",
//     id: 12,
//     category: "Vitus",
//     bikeName: "Vitus Escarpe 27.5 CRS",
//     price: 4670.0,
//     srcArray: [
//       { id: 1, src: bike12 },
//       { id: 2, src: bike12f1 },
//       { id: 3, src: bike12f2 },
//       { id: 4, src: bike12f3 },
//     ],
//   },
// ];
